name: CI - Develop/Next/Main

on:
  pull_request:
    branches: [ develop, next, main ]
    paths:
      - template/**/*

jobs:
  run_lint_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/run-linters
  run_test:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/run-tests
    needs: [ run_lint ]
