name: CI

on:
  push:
    branches:
    - '*'

jobs:
  install-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          cd template
          yarn install
      - name: Run linters
        run: |
          cp _prettierrc.js .prettierrc.js
          cp _eslintrc.js .eslintrc.js
          yarn lint
      - name: Run tests
        run: |
          cp src/Config/index.example.js src/Config/index.js
          yarn test
