name: CD workflow to NPM publish

on:
  workflow_call:
    inputs:
      checkout_ref:
        type: string
        required: true
      tag:
        type: string
        required: true
    secrets:
      NPM:
        required: true
      GITHUB:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.checkout_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - run: |
          git config --global user.name "RNB Bot"
          git config --global user.email "jeremy.dolle34@gmail.com"
          npm --no-git-tag-version version ${{ inputs.tag }}
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          fi
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM }}
      - name: Commit and push
        run: |
          git add .
          git commit -am "üè∑Ô∏è(version) Update boilerplate to version ${{ inputs.tag }}"
          git push
        env:
          github-token: ${{ secrets.GITHUB }}
